server.port=${PORT:8083}
spring.application.name=purchase-service

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.security=DEBUG